from .models import UserPreference


UI_TEXT = {
    "fr": {
        "tagline": "Organiser. Suivre. Avancer.",
        "nav_dashboard": "Dashboard",
        "nav_tasks": "Taches",
        "nav_habits": "Habitudes",
        "nav_schedule": "Emploi du temps",
        "nav_statistics": "Statistiques",
        "nav_settings": "Parametres",
        "nav_home": "Accueil",
        "nav_planning": "Planning",
        "nav_more": "Plus",
        "logout": "Deconnexion",
        "settings_eyebrow": "Parametres",
        "settings_title": "Preferences",
        "settings_save": "Enregistrer",
        "settings_reset_title": "Reinitialisation",
        "settings_reset_text": "Supprime uniquement tes taches, habitudes et activites. Les autres utilisateurs ne sont pas touches.",
        "settings_reset_button": "Reinitialiser les donnees",
        "edit_eyebrow": "Edition",
        "cancel": "Annuler",
        "dashboard_greeting": "Bonjour",
        "dashboard_title": "Ta semaine en un coup d'oeil",
        "add_task": "Ajouter une tache",
        "planned_tasks": "Taches prevues",
        "done_tasks": "Taches terminees",
        "done_habits": "Habitudes faites",
        "important_goals": "Objectifs importants",
        "next_task": "Prochaine tache",
        "view_all": "Tout voir",
        "at": "a",
        "no_urgent_task": "Aucune tache urgente. Tu peux planifier la suite calmement.",
        "today_habits": "Habitudes du jour",
        "manage": "Gerer",
        "add_habit_prompt": "Ajoute une habitude pour suivre ton rythme quotidien.",
        "today_tasks": "Taches du jour",
        "add": "Ajouter",
        "no_time": "Sans heure",
        "nothing_today": "Rien de prevu aujourd'hui.",
        "tasks_eyebrow": "Taches",
        "tasks_title": "Priorites et actions",
        "new_task": "Nouvelle tache",
        "no_detail": "Aucun detail.",
        "finish": "Terminer",
        "edit": "Modifier",
        "delete": "Supprimer",
        "no_task": "Aucune tache pour le moment.",
        "habits_eyebrow": "Habitudes",
        "habits_title": "Routines quotidiennes",
        "new_habit": "Nouvelle habitude",
        "done": "Faite",
        "todo": "A faire",
        "active_routine": "Routine active.",
        "uncheck": "Decocher",
        "check": "Cocher",
        "no_habit": "Aucune habitude active.",
        "stats_eyebrow": "Statistiques",
        "stats_title": "Progression de la semaine",
        "productivity": "Productivite",
        "checked_habits": "Habitudes cochees",
        "best_habit": "Meilleure habitude",
        "daily_activity": "Activite quotidienne",
        "schedule_eyebrow": "Emploi du temps",
        "week_from": "Semaine du",
        "week_to": "au",
        "add_habit": "Ajouter une habitude",
        "export_pdf": "Exporter PDF",
        "add_activity": "Ajouter une activite",
        "previous_week": "Semaine precedente",
        "today": "Aujourd'hui",
        "next_week": "Semaine suivante",
        "reminder": "Rappel",
        "to_do": "A faire",
        "routine": "Routine",
        "free": "Libre",
        "add_slot_task": "Ajouter tache",
        "add_slot_habit": "Ajouter habitude",
        "add_slot_activity": "Ajouter activite",
    },
    "en": {
        "tagline": "Organize. Track. Move forward.",
        "nav_dashboard": "Dashboard",
        "nav_tasks": "Tasks",
        "nav_habits": "Habits",
        "nav_schedule": "Schedule",
        "nav_statistics": "Statistics",
        "nav_settings": "Settings",
        "nav_home": "Home",
        "nav_planning": "Planning",
        "nav_more": "More",
        "logout": "Log out",
        "settings_eyebrow": "Settings",
        "settings_title": "Preferences",
        "settings_save": "Save",
        "settings_reset_title": "Reset",
        "settings_reset_text": "Deletes only your tasks, habits and activities. Other users are not affected.",
        "settings_reset_button": "Reset data",
        "edit_eyebrow": "Edit",
        "cancel": "Cancel",
        "dashboard_greeting": "Hello",
        "dashboard_title": "Your week at a glance",
        "add_task": "Add a task",
        "planned_tasks": "Planned tasks",
        "done_tasks": "Completed tasks",
        "done_habits": "Completed habits",
        "important_goals": "Important goals",
        "next_task": "Next task",
        "view_all": "View all",
        "at": "at",
        "no_urgent_task": "No urgent task. You can calmly plan what comes next.",
        "today_habits": "Today's habits",
        "manage": "Manage",
        "add_habit_prompt": "Add a habit to track your daily rhythm.",
        "today_tasks": "Today's tasks",
        "add": "Add",
        "no_time": "No time",
        "nothing_today": "Nothing planned today.",
        "tasks_eyebrow": "Tasks",
        "tasks_title": "Priorities and actions",
        "new_task": "New task",
        "no_detail": "No details.",
        "finish": "Finish",
        "edit": "Edit",
        "delete": "Delete",
        "no_task": "No task yet.",
        "habits_eyebrow": "Habits",
        "habits_title": "Daily routines",
        "new_habit": "New habit",
        "done": "Done",
        "todo": "To do",
        "active_routine": "Active routine.",
        "uncheck": "Uncheck",
        "check": "Check",
        "no_habit": "No active habit.",
        "stats_eyebrow": "Statistics",
        "stats_title": "Weekly progress",
        "productivity": "Productivity",
        "checked_habits": "Checked habits",
        "best_habit": "Best habit",
        "daily_activity": "Daily activity",
        "schedule_eyebrow": "Schedule",
        "week_from": "Week from",
        "week_to": "to",
        "add_habit": "Add a habit",
        "export_pdf": "Export PDF",
        "add_activity": "Add an activity",
        "previous_week": "Previous week",
        "today": "Today",
        "next_week": "Next week",
        "reminder": "Reminder",
        "to_do": "To do",
        "routine": "Routine",
        "free": "Free",
        "add_slot_task": "Add task",
        "add_slot_habit": "Add habit",
        "add_slot_activity": "Add activity",
    },
    "mg": {
        "tagline": "Mandamina. Manara-maso. Mandroso.",
        "nav_dashboard": "Tabilao",
        "nav_tasks": "Asa",
        "nav_habits": "Fahazarana",
        "nav_schedule": "Fandaharam-potoana",
        "nav_statistics": "Antontan'isa",
        "nav_settings": "Kirakira",
        "nav_home": "Fandraisana",
        "nav_planning": "Fandaharam-potoana",
        "nav_more": "Hafa",
        "logout": "Hivoaka",
        "settings_eyebrow": "Kirakira",
        "settings_title": "Safidy",
        "settings_save": "Tehirizo",
        "settings_reset_title": "Famerenana",
        "settings_reset_text": "Mamafa ny asanao, fahazarana ary hetsikao ihany. Tsy voakasika ny mpampiasa hafa.",
        "settings_reset_button": "Avereno ny angona",
        "edit_eyebrow": "Fanovana",
        "cancel": "Aoka ihany",
        "dashboard_greeting": "Salama",
        "dashboard_title": "Topimaso amin'ny herinandronao",
        "add_task": "Ampio asa",
        "planned_tasks": "Asa voalahatra",
        "done_tasks": "Asa vita",
        "done_habits": "Fahazarana vita",
        "important_goals": "Tanjona lehibe",
        "next_task": "Asa manaraka",
        "view_all": "Jereo rehetra",
        "at": "amin'ny",
        "no_urgent_task": "Tsy misy asa maika. Afaka mandamina moramora ianao.",
        "today_habits": "Fahazarana anio",
        "manage": "Tantano",
        "add_habit_prompt": "Ampio fahazarana hanarahana ny gadonao isan'andro.",
        "today_tasks": "Asa anio",
        "add": "Ampio",
        "no_time": "Tsy misy ora",
        "nothing_today": "Tsy misy voalahatra anio.",
        "tasks_eyebrow": "Asa",
        "tasks_title": "Laharam-pahamehana sy hetsika",
        "new_task": "Asa vaovao",
        "no_detail": "Tsy misy antsipiriany.",
        "finish": "Vitao",
        "edit": "Ovay",
        "delete": "Fafao",
        "no_task": "Tsy mbola misy asa.",
        "habits_eyebrow": "Fahazarana",
        "habits_title": "Fanao isan'andro",
        "new_habit": "Fahazarana vaovao",
        "done": "Vita",
        "todo": "Hatao",
        "active_routine": "Fahazarana mandeha.",
        "uncheck": "Esory",
        "check": "Mariho",
        "no_habit": "Tsy misy fahazarana mandeha.",
        "stats_eyebrow": "Antontan'isa",
        "stats_title": "Fandrosoan'ny herinandro",
        "productivity": "Fahavokarana",
        "checked_habits": "Fahazarana voamarika",
        "best_habit": "Fahazarana tsara indrindra",
        "daily_activity": "Hetsika isan'andro",
        "schedule_eyebrow": "Fandaharam-potoana",
        "week_from": "Herinandro manomboka",
        "week_to": "hatramin'ny",
        "add_habit": "Ampio fahazarana",
        "export_pdf": "Hamoaka PDF",
        "add_activity": "Ampio hetsika",
        "previous_week": "Herinandro teo aloha",
        "today": "Anio",
        "next_week": "Herinandro manaraka",
        "reminder": "Fampahatsiahivana",
        "to_do": "Hatao",
        "routine": "Fanao",
        "free": "Malalaka",
        "add_slot_task": "Ampio asa",
        "add_slot_habit": "Ampio fahazarana",
        "add_slot_activity": "Ampio hetsika",
    },
}


def ui_text(request):
    language = "fr"
    if request.user.is_authenticated:
        language = request.session.get("myweek_language") or language
        try:
            language = request.user.preference.language
        except UserPreference.DoesNotExist:
            pass

    if language not in UI_TEXT:
        language = "fr"

    return {"ui": UI_TEXT[language], "current_language": language}
