# Generated by Django 6.0.6 on 2026-07-02 10:53

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('frequency', models.CharField(choices=[('daily', 'Tous les jours'), ('weekdays', 'Jours de semaine'), ('weekly', 'Une fois par semaine'), ('custom', 'Personnalisee')], default='daily', max_length=24, verbose_name='Frequence')),
                ('target_value', models.PositiveIntegerField(default=1, verbose_name='Objectif')),
                ('target_unit', models.CharField(blank=True, default='fois', max_length=40, verbose_name='Unite')),
                ('reminder_time', models.TimeField(blank=True, null=True, verbose_name='Rappel')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('subtitle', models.CharField(blank=True, max_length=160, verbose_name='Details')),
                ('day', models.PositiveSmallIntegerField(choices=[(0, 'Lundi'), (1, 'Mardi'), (2, 'Mercredi'), (3, 'Jeudi'), (4, 'Vendredi'), (5, 'Samedi'), (6, 'Dimanche')], verbose_name='Jour')),
                ('start_time', models.TimeField(verbose_name='Heure de debut')),
                ('end_time', models.TimeField(verbose_name='Heure de fin')),
                ('color', models.CharField(default='#22C55E', max_length=20, verbose_name='Couleur')),
                ('item_type', models.CharField(choices=[('course', 'Cours'), ('work', 'Travail'), ('personal', 'Personnel'), ('other', 'Autre')], default='other', max_length=24, verbose_name='Type')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['day', 'start_time', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160, verbose_name='Titre')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('date', models.DateField(verbose_name='Date')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='Heure de debut')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='Heure de fin')),
                ('priority', models.CharField(choices=[('low', 'Faible'), ('medium', 'Moyenne'), ('high', 'Importante')], default='medium', max_length=16, verbose_name='Priorite')),
                ('status', models.CharField(choices=[('todo', 'A faire'), ('progress', 'En cours'), ('done', 'Terminee')], default='todo', max_length=16, verbose_name='Statut')),
                ('category', models.CharField(blank=True, max_length=80, verbose_name='Categorie')),
                ('is_important', models.BooleanField(default=False, verbose_name='Objectif important')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['date', 'start_time', '-is_important', 'title'],
            },
        ),
        migrations.CreateModel(
            name='HabitLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate)),
                ('is_done', models.BooleanField(default=True)),
                ('value_done', models.PositiveIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('habit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='planner.habit')),
            ],
            options={
                'ordering': ['-date', 'habit__title'],
                'constraints': [models.UniqueConstraint(fields=('habit', 'date'), name='one_habit_log_per_day')],
            },
        ),
    ]
