# Generated by Django 6.0.6 on 2026-07-02 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0002_habit_user_scheduleitem_user_task_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='habit',
            name='custom_days',
            field=models.CharField(blank=True, max_length=32, verbose_name='Jours personnalises'),
        ),
    ]
